### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by kelly6** [apache/rocketmq-client-go#166] opened 2019-08-21 11:15 UTC
branch:origin/native

I start 12 clients with the same group, Some clients crashed after a few minutes.
Here is its traceback:

```
fatal error: concurrent map read and map write

goroutine 52 [running]:
runtime.throw(0x5e51b9, 0x21)
    /usr/lib/go/src/runtime/panic.go:617 +0x72 fp=0xc001cebcd8 sp=0xc001cebca8 pc=0x42ce92
runtime.mapaccess1_faststr(0x5a3f60, 0xc00145e2d0, 0x5df7c4, 0xa, 0xc0002760d0)
    /usr/lib/go/src/runtime/map_faststr.go:21 +0x469 fp=0xc001cebd48 sp=0xc001cebcd8 pc=0x4134c9
github.com/apache/rocketmq-client-go/consumer.(*processQueue).putMessage(0xc0002bcd00, 0xc00024c000, 0x1, 0x1)
    /home/kelly/code/git/rocketmq-client-go/consumer/process_queue.go:104 +0x221 fp=0xc001cebdd8 sp=0xc001cebd48 pc=0x568001
github.com/apache/rocketmq-client-go/consumer.(*pushConsumer).pullMessage(0xc0001cc9c0, 0xc0002880f0)
    /home/kelly/code/git/rocketmq-client-go/consumer/push_consumer.go:474 +0x1a2d fp=0xc001cebfb0 sp=0xc001cebdd8 pc=0x56bfbd
github.com/apache/rocketmq-client-go/consumer.(*pushConsumer).Start.func1.2.1(0xc0001cc9c0, 0xc0002880f0)
    /home/kelly/code/git/rocketmq-client-go/consumer/push_consumer.go:141 +0x35 fp=0xc001cebfd0 sp=0xc001cebfb0 pc=0x573725
runtime.goexit()
    /usr/lib/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc001cebfd8 sp=0xc001cebfd0 pc=0x4584e1
created by github.com/apache/rocketmq-client-go/consumer.(*pushConsumer).Start.func1.2
    /home/kelly/code/git/rocketmq-client-go/consumer/push_consumer.go:140 +0x4a

```

test code:

`examples/consumer/simple/main.go`

**Comment by wenfengwang** [comment] 2019-08-23 02:34
the duplicated issue: https://github.com/apache/rocketmq-client-go/issues/139

**Comment by kelly6** [comment] 2019-08-23 06:13
> the duplicated issue: #139

@wenfengwang 
I'm not sure. The call stack looks a little different. #139 crashs in update.

Does these functions change the same map?

**Comment by ShannonDing** [comment] 2019-08-23 07:58
@kelly6  Lock was added when local offset was updated in PR #164, Could you please have a test again in your ENV after PR #146 merged?

**Comment by wenfengwang** [comment] 2019-08-23 08:05
@ShannonDing @kelly6 It seems to my mistake. the issue https://github.com/apache/rocketmq-client-go/issues/139 is an error that happened when access offset concurrently, but the issue is access `message.Properties` concurrently. so the issue is different from https://github.com/apache/rocketmq-client-go/issues/139. I will fix it.

**Comment by kelly6** [comment] 2019-08-23 08:36
@ShannonDing   As @wenfengwang commented, those two issue may not be the same, I will run my test when he fix this.

**Comment by wenfengwang** [comment] 2019-09-10 03:26
fixed by https://github.com/apache/rocketmq-client-go/pull/197

**Comment by ShannonDing** [comment] 2019-09-11 07:07
close due to #197

**Closed by ShannonDing** 2019-09-11 07:07 UTC
Labels: bug
