### ISSUE TITLE
[MASTER] The consumer does not work after running for some time

### ISSUE THREAD

**Issue by hanzhonghua0927** [apache/rocketmq-client-go#337] opened 2019-12-21 07:34 UTC
52/5000 
A process starts with multiple consumers, and each consumer has a group corresponding to a topic. The consumers of this process do not consume after running for a period of time

**Comment by hanzhonghua0927** [comment] 2019-12-25 04:07
@ShannonDing

**Comment by ShannonDing** [comment] 2020-01-08 06:08
it may caused by CPP core.  this issue will be transferred to the CPP client project. I will close it first.

**Closed by ShannonDing** 2020-01-08 06:08 UTC
Labels: help wanted
